application: wondapad
# changes in first two positions force an upgrade popup in clients, third one does not (use for minor updates where old js is fine)
# Please keep syntax, eg 2-0-0
version: 1-6-4
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"

inbound_services:
- warmup


handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico
  expiration: "1d"   
  secure: always  

- url: /apple-touch-icon-precomposed.png
  static_files: application/static/img/apple-touch-icon-precomposed.png
  upload: application/static/img/apple-touch-icon-precomposed.png 
  mime_type: image/png 
  expiration: "1d"   
  secure: always  

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt
  secure: always  

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /static
  static_dir: application/static
  secure: always 
  expiration: "365d" 
  http_headers:
    Vary: Accept-Encoding  

- url: /static/img
  static_dir: application/static/img
  secure: always 
  mime_type: image/png   
  expiration: "365d" 
  http_headers:
    Vary: Accept-Encoding      

- url: /json
  static_dir: application/static/json
  secure: always  

- url: .*
  script: run.application.app
  secure: always
