application: wondapad
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"

inbound_services:
- warmup

pagespeed:
  url_blacklist:
  - http://www.hiroapp.com/docs/*
  - http://www.hiroapp.com/relevant
  - http://www.hiroapp.com/analyze
  enabled_rewriters:
  - MinifyCss
  - CollapseWhitespace
  disabled_rewriters:
  - InlineCss
  - ImageConvertToJpeg
  - ImageResize
  - LazyloadImages
  - InlinePreviewImages
  - MoveCssToHead
  - CombineCss
  - CombineJs
  - WebpOptimization
  - ImageRecompressJpeg 
  - ImageProgressiveJpeg
  - ConvertMetaTags


handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico
  secure: always  

- url: /apple-touch-icon-precomposed.png
  static_files: application/static/img/apple-touch-icon-precomposed.png
  upload: application/static/img/apple-touch-icon-precomposed.png  
  secure: always  

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt
  secure: always  

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /static
  static_dir: application/static
  secure: always  

- url: /json
  static_dir: application/static/json
  secure: always  

- url: .*
  script: run.application.app
  secure: always